TimerClass: timeclass Module Reference
timeclass Module Reference
The TimeClass module contains the TTime class used by the TTimer class for practical timing.
Data Types
module ttime
The TTime class contains all time functionality with regard to a single time stamp.
Functions/Subroutines
pure type(ttime) function constructor ()
Constructor for the TTime class.
subroutine settime (this)
Function to set the TTime instance to the current time, with millisecond resolution.
pure subroutine calculatejdn (this)
Calculating the Julian Day number based on the Gregorian date set in the TTime object.
pure subroutine setjdn (this, JDN, IO)
Set the Julian Day Number of a TTime instance manually.
pure integer(kind=4) function getjuliandaynumber (this)
Function returning the Julian Day Number as a 4-byte integer.
pure subroutine setgregoriandatefromjdn (this, IO)
Subroutine which transforms the set Julian Day Number into a Gregorian Calender date.
pure subroutine copy (this, from)
Function to copy one TTime instance to the current one via the "=" assignment. This is the function performing the actual operator overloading.
pure type(ttime) function add (this, that)
Function to add two TTime instance via the "+" operator. This is the function performing the actual operator overloading.
pure type(ttime) function subtract (this, that)
Function to subtract two TTime instance via the "-" operator. This is the function performing the actual operator overloading.
pure logical function isleapyear (this)
Function returning true/false if the year of the TTime instance is a leap year.
pure character(len=255) function gettimestring (this, fmt)
Returns a string with the time as a string.
pure real(dp) function gettimeseconds (this)
Function returning the time in (fractional) seconds (double precision).
subroutine destructor (this)
Destructor of the TTime object instance.
Detailed Description
The TimeClass module contains the TTime class used by the TTimer class for practical timing.
Author
Dr. Dr. Danny E. P. Vanpoucke
Version
2.0-3 (upgrades deprecated timing module)
Date
19-03-2020
Copyright
https://dannyvanpoucke.be
Warning
Internally, Julian Day Numbers are used to compare dates. As a result, negative dates are not accepted. If such dates are created (e.g., due to a subtraction), then the date is set to zero.
This module makes use of:
nothing; this module is fully independent
Function/Subroutine Documentation
add()
pure type(ttime) function timeclass::add (class(ttime), intent(in) this, class(ttime), intent(in) that) private
Function to add two TTime instance via the "+" operator. This is the function performing the actual operator overloading.
Adding two full dates is maybe a bit strange to do. In our case, we don't just add the days and add the months, but we add the days of the year (via their Julian Day Numbers) and transform these back to months and days. (why keep life simple if we can make it complicated?)
usage:
total = this + that
This line also calls the assignment operator.
Parameters
[in] this The TTime instance before the "+" operator.
[in] that The TTime instance after the "+" operator.
Returns
Total The TTime instance representing the sum.
Definition at line 264 of file TimeClass.f03.
Referenced by timeclass::ttime::operator().
calculatejdn()
pure subroutine timeclass::calculatejdn (class(ttime), intent(inout) this) private
Calculating the Julian Day number based on the Gregorian date set in the TTime object.
In practice the Gregorian calender date set in the TTime instance is transformed into a Julian Day Number, and stored in the instance as ttime::jdn.
Parameters
[in,out] this The TTime instance being called.
Definition at line 139 of file TimeClass.f03.
constructor()
pure type(ttime) function timeclass::constructor private
Constructor for the TTime class.
Note
This constructor does not set the time. It just enters zero's.
usage:
Type(TTime) :: T
t = ttime()
Returns
Time An instance of the TTime class.
Definition at line 98 of file TimeClass.f03.
Referenced by timeclass::ttime::destructor(), and timerclass::ttimer::destructor().
copy()
pure subroutine timeclass::copy (class(ttime), intent(inout) this, class(ttime), intent(in) from) private
Function to copy one TTime instance to the current one via the "=" assignment. This is the function performing the actual operator overloading.
usage:
tnew = told
Parameters
[in,out] this The TTime instance before the "=" assignment.
[in] from The TTime instance after the "=" assignment.
Definition at line 233 of file TimeClass.f03.
Referenced by timeclass::ttime::assignment(), and timerclass::ttimer::assignment().
destructor()
subroutine timeclass::destructor (type(ttime) this) private
Destructor of the TTime object instance.
This subroutine is automatically called upon finalization of the instance.
Parameters
[in,out] this The instance of the TTime class in need of destruction.
Definition at line 419 of file TimeClass.f03.
Referenced by timeclass::ttime::destructor(), and timerclass::ttimer::destructor().
getjuliandaynumber()
pure integer(kind=4) function timeclass::getjuliandaynumber (class(ttime), intent(in) this) private
Function returning the Julian Day Number as a 4-byte integer.
Use integer(kind=4).
Parameters
[in,out] this The TTime instance being called.
Returns
JDN The integer Julian Day Number.
Definition at line 184 of file TimeClass.f03.
gettimeseconds()
pure real(dp) function timeclass::gettimeseconds (class(ttime), intent(in) this) private
Function returning the time in (fractional) seconds (double precision).
Parameters
[in] this The TTime instance.
Returns
sec total number of seconds representing the "time" as a double precision value.
Definition at line 402 of file TimeClass.f03.
gettimestring()
pure character(len=255) function timeclass::gettimestring (class(ttime), intent(in) this, character(len=*), intent(in), optional fmt) private
Returns a string with the time as a string.
Format options for fmt:
full: dd/mm/yyyy hh:mm:ss.mmm
date: dd/mm/yyyy
time: hh:mm:ss.mmm
days: Gives the total time in fractional days (best used for time-differences). Uses the Julian Day Number.
hours: Same as days, but transformed to hours.
seconds: Same as days, but transformed to seconds.
Parameters
[in] this The TTime instance transform into a string.
[in] fmt String representing the possible formatting. [OPTIONAL, DEFAULT = full]
Returns
TS String with formatted time.
Definition at line 356 of file TimeClass.f03.
isleapyear()
pure logical function timeclass::isleapyear (class(ttime), intent(in) this) private
Function returning true/false if the year of the TTime instance is a leap year.
A leap year is a multiple of 4, but not 100, unless 400
Parameters
[in] this The TTime instance to check the leap-year.
Returns
Leap Boolean indicating if the year is a leap-year.
Definition at line 327 of file TimeClass.f03.
setgregoriandatefromjdn()
pure subroutine timeclass::setgregoriandatefromjdn (class(ttime), intent(inout) this, integer, intent(out), optional IO) private
Subroutine which transforms the set Julian Day Number into a Gregorian Calender date.
Note
The routine is only valid for a JDN>=0.
Parameters
[in,out] this The TTime instance being called.
[out] IO Returns 0 on success, and -1 for failure. [OPTIONAL ]
Definition at line 199 of file TimeClass.f03.
setjdn()
pure subroutine timeclass::setjdn (class(ttime), intent(inout) this, integer(kind=4), intent(in) JDN, integer, intent(out), optional IO) private
Set the Julian Day Number of a TTime instance manually.
Note
The Julian Day Number should be >=0. For negative values it is set to 0, and an error value is set to IO
Parameters
[in,out] this The TTime instance being called.
[in] JDN A positive integer(kind=4) value representing a valid Julian Day Number.
[out] IO Integer value returning 0 upon success, and a negative value(=JDN) in case of failure.
Definition at line 158 of file TimeClass.f03.
settime()
subroutine timeclass::settime (class(ttime), intent(inout) this) private
Function to set the TTime instance to the current time, with millisecond resolution.
Note
As this subroutine uses the date_and_time intrinsic it is an impure subroutine.
Parameters
[in,out] this The TTime instance being called.
Definition at line 116 of file TimeClass.f03.
subtract()
pure type(ttime) function timeclass::subtract (class(ttime), intent(in) this, class(ttime), intent(in) that) private
Function to subtract two TTime instance via the "-" operator. This is the function performing the actual operator overloading.
usage:
total = this - that
This line also calls the assignment operator.
Note
The result should remain a positive number.
Parameters
[in] this The TTime instance before the "-" operator.
[in] that The TTime instance after the "-" operator.
Returns
Total The TTime instance representing the difference.
Definition at line 300 of file TimeClass.f03.
Referenced by timeclass::ttime::operator().