TimerClass: timeclass::ttime Module Reference
timeclass::ttime Module Reference
The TTime class contains all time functionality with regard to a single time stamp.
Public Member Functions
procedure, pass, public settime
Function to set the TTime instance to the current time, with millisecond resolution.
procedure, pass, public getjuliandaynumber
Function returning the Julian Day Number as a 4-byte integer.
procedure, pass, public isleapyear
Function returning true/false if the year of the TTime instance is a leap year.
procedure, pass, public gettimestring
Returns a string with the time as a string.
procedure, pass, public gettimeseconds
Function returning the time in (fractional) seconds (double precision).
generic, public assignment => copy
Function to copy one TTime instance to the current one via the "=" assignment. This is the function performing the actual operator overloading.
generic, public operator => add
Function to add two TTime instance via the "+" operator. This is the function performing the actual operator overloading.
generic, public operator => subtract
Function to subtract two TTime instance via the "-" operator. This is the function performing the actual operator overloading.
Protected Member Functions
final destructor
Destructor of the TTime object instance.
Private Member Functions
procedure, pass(this) calculatejdn
Calculating the Julian Day number based on the Gregorian date set in the TTime object.
procedure, pass(this) setjdn
Set the Julian Day Number of a TTime instance manually.
procedure, pass(this) setgregoriandatefromjdn
Subroutine which transforms the set Julian Day Number into a Gregorian Calender date.
procedure, pass(this) copy
Function to copy one TTime instance to the current one via the "=" assignment. This is the function performing the actual operator overloading.
procedure, pass(this) add
Function to add two TTime instance via the "+" operator. This is the function performing the actual operator overloading.
procedure, pass(this) subtract
Function to subtract two TTime instance via the "-" operator. This is the function performing the actual operator overloading.
pure type(ttime) function constructor ()
Constructor for the TTime class.
Private Attributes
integer year
The year.
integer month
The month (as integer).
integer day
Day of the month.
integer(kind=4) jdn
The Julian Day Number, as a long-int (4-byte)
real daysecs
Number of seconds of the day, with millisecond resolution.
Detailed Description
The TTime class contains all time functionality with regard to a single time stamp.
Definition at line 50 of file TimeClass.f03.
Member Function/Subroutine Documentation
add()
procedure, pass(this) timeclass::ttime::add private
Function to add two TTime instance via the "+" operator. This is the function performing the actual operator overloading.
Adding two full dates is maybe a bit strange to do. In our case, we don't just add the days and add the months, but we add the days of the year (via their Julian Day Numbers) and transform these back to months and days. (why keep life simple if we can make it complicated?)
usage:
total = this + that
This line also calls the assignment operator.
Parameters
[in] this The TTime instance before the "+" operator.
[in] that The TTime instance after the "+" operator.
Returns
Total The TTime instance representing the sum.
Definition at line 65 of file TimeClass.f03.
assignment()
generic, public timeclass::ttime::assignment
Function to copy one TTime instance to the current one via the "=" assignment. This is the function performing the actual operator overloading.
usage:
tnew = told
Parameters
[in,out] this The TTime instance before the "=" assignment.
[in] from The TTime instance after the "=" assignment.
Definition at line 70 of file TimeClass.f03.
References timeclass::copy().
calculatejdn()
procedure, pass(this) timeclass::ttime::calculatejdn private
Calculating the Julian Day number based on the Gregorian date set in the TTime object.
In practice the Gregorian calender date set in the TTime instance is transformed into a Julian Day Number, and stored in the instance as ttime::jdn.
Parameters
[in,out] this The TTime instance being called.
Definition at line 60 of file TimeClass.f03.
constructor()
pure type(ttime) function timeclass::ttime::constructor private
Constructor for the TTime class.
Note
This constructor does not set the time. It just enters zero's.
usage:
Type(TTime) :: T
t = ttime()
Returns
Time An instance of the TTime class.
Definition at line 98 of file TimeClass.f03.
copy()
procedure, pass(this) timeclass::ttime::copy private
Function to copy one TTime instance to the current one via the "=" assignment. This is the function performing the actual operator overloading.
usage:
tnew = told
Parameters
[in,out] this The TTime instance before the "=" assignment.
[in] from The TTime instance after the "=" assignment.
Definition at line 64 of file TimeClass.f03.
destructor()
final timeclass::ttime::destructor final protected
Destructor of the TTime object instance.
This subroutine is automatically called upon finalization of the instance.
Parameters
[in,out] this The instance of the TTime class in need of destruction.
Definition at line 74 of file TimeClass.f03.
References timeclass::constructor(), and timeclass::destructor().
getjuliandaynumber()
procedure, pass, public timeclass::ttime::getjuliandaynumber
Function returning the Julian Day Number as a 4-byte integer.
Use integer(kind=4).
Parameters
[in,out] this The TTime instance being called.
Returns
JDN The integer Julian Day Number.
Definition at line 63 of file TimeClass.f03.
gettimeseconds()
procedure, pass, public timeclass::ttime::gettimeseconds
Function returning the time in (fractional) seconds (double precision).
Parameters
[in] this The TTime instance.
Returns
sec total number of seconds representing the "time" as a double precision value.
Definition at line 69 of file TimeClass.f03.
gettimestring()
procedure, pass, public timeclass::ttime::gettimestring
Returns a string with the time as a string.
Format options for fmt:
full: dd/mm/yyyy hh:mm:ss.mmm
date: dd/mm/yyyy
time: hh:mm:ss.mmm
days: Gives the total time in fractional days (best used for time-differences). Uses the Julian Day Number.
hours: Same as days, but transformed to hours.
seconds: Same as days, but transformed to seconds.
Parameters
[in] this The TTime instance transform into a string.
[in] fmt String representing the possible formatting. [OPTIONAL, DEFAULT = full]
Returns
TS String with formatted time.
Definition at line 68 of file TimeClass.f03.
isleapyear()
procedure, pass, public timeclass::ttime::isleapyear
Function returning true/false if the year of the TTime instance is a leap year.
A leap year is a multiple of 4, but not 100, unless 400
Parameters
[in] this The TTime instance to check the leap-year.
Returns
Leap Boolean indicating if the year is a leap-year.
Definition at line 67 of file TimeClass.f03.
operator() [1/2]
generic, public timeclass::ttime::operator
Function to add two TTime instance via the "+" operator. This is the function performing the actual operator overloading.
Adding two full dates is maybe a bit strange to do. In our case, we don't just add the days and add the months, but we add the days of the year (via their Julian Day Numbers) and transform these back to months and days. (why keep life simple if we can make it complicated?)
usage:
total = this + that
This line also calls the assignment operator.
Parameters
[in] this The TTime instance before the "+" operator.
[in] that The TTime instance after the "+" operator.
Returns
Total The TTime instance representing the sum.
Definition at line 71 of file TimeClass.f03.
References timeclass::add().
operator() [2/2]
generic, public timeclass::ttime::operator
Function to subtract two TTime instance via the "-" operator. This is the function performing the actual operator overloading.
usage:
total = this - that
This line also calls the assignment operator.
Note
The result should remain a positive number.
Parameters
[in] this The TTime instance before the "-" operator.
[in] that The TTime instance after the "-" operator.
Returns
Total The TTime instance representing the difference.
Definition at line 72 of file TimeClass.f03.
References timeclass::subtract().
setgregoriandatefromjdn()
procedure, pass(this) timeclass::ttime::setgregoriandatefromjdn private
Subroutine which transforms the set Julian Day Number into a Gregorian Calender date.
Note
The routine is only valid for a JDN>=0.
Parameters
[in,out] this The TTime instance being called.
[out] IO Returns 0 on success, and -1 for failure. [OPTIONAL ]
Definition at line 62 of file TimeClass.f03.
setjdn()
procedure, pass(this) timeclass::ttime::setjdn private
Set the Julian Day Number of a TTime instance manually.
Note
The Julian Day Number should be >=0. For negative values it is set to 0, and an error value is set to IO
Parameters
[in,out] this The TTime instance being called.
[in] JDN A positive integer(kind=4) value representing a valid Julian Day Number.
[out] IO Integer value returning 0 upon success, and a negative value(=JDN) in case of failure.
Definition at line 61 of file TimeClass.f03.
settime()
procedure, pass, public timeclass::ttime::settime
Function to set the TTime instance to the current time, with millisecond resolution.
Note
As this subroutine uses the date_and_time intrinsic it is an impure subroutine.
Parameters
[in,out] this The TTime instance being called.
Definition at line 59 of file TimeClass.f03.
subtract()
procedure, pass(this) timeclass::ttime::subtract private
Function to subtract two TTime instance via the "-" operator. This is the function performing the actual operator overloading.
usage:
total = this - that
This line also calls the assignment operator.
Note
The result should remain a positive number.
Parameters
[in] this The TTime instance before the "-" operator.
[in] that The TTime instance after the "-" operator.
Returns
Total The TTime instance representing the difference.
Definition at line 66 of file TimeClass.f03.
Member Data Documentation
day
integer timeclass::ttime::day private
Day of the month.
Definition at line 54 of file TimeClass.f03.
daysecs
real timeclass::ttime::daysecs private
Number of seconds of the day, with millisecond resolution.
Definition at line 56 of file TimeClass.f03.
jdn
integer(kind=4) timeclass::ttime::jdn private
The Julian Day Number, as a long-int (4-byte)
Definition at line 55 of file TimeClass.f03.
month
integer timeclass::ttime::month private
The month (as integer).
Definition at line 53 of file TimeClass.f03.
year
integer timeclass::ttime::year private
The year.
Definition at line 52 of file TimeClass.f03.
The documentation for this module was generated from the following file:
TimeClass.f03