TimerClass: timerclass::ttimer Module Reference
timerclass::ttimer Module Reference
A class for keeping track of time in calculations, by creating a list of timestamps.
Public Member Functions
procedure, pass, public start
Start the TTimer instance (clean start, everything is reset). If the timer was already running it is reset first.
procedure, pass, public interrupt
Puts the TTimer instance on hold.
procedure, pass, public resume
Restart the TTimer instance after a pause. If the timer is not paused, nothing will happen and TS=-1 is returned.
procedure, pass, public addtimeflag
Add an additional timestamp without changing the status (running/paused) of the TTimer instance.
procedure, pass, public stoptimer
Stops the TTimer instance (terminal fashion...no restart possible).
procedure, pass, public reset
Start the TTimer instance. If the timer was already running it is reset first.
procedure, pass, public printelapsedtimereport
Print small timings report to unit UN.
procedure, pass, public getelapsedtimestring
Returns a string representing the elapsed time. +.
generic, public assignment => copy
Function to copy one TTimer instance to the current one via the "=" assignment.
generic, public getelapsedtime => getelapsedtime_total, getelapsedtime_steps
Generic interface to the GetElapsedTime_total and GetElapsedTime_steps methods of the TTimer class.
Protected Member Functions
final destructor
Destructor of the TTimer class. Cleans up the instance upon finalization.
Private Member Functions
procedure, pass(this) getelapsedtime_total
Returns the number of seconds which elapsed between the start and stop timestamps.
procedure, pass(this) getelapsedtime_steps
Returns the number of seconds which elapsed between two timestamps. This is always a positive value.
procedure, pass(this) copy
Function to copy one TTimer instance to the current one via the "=" assignment.
procedure, pass(this) addtimestamp
Add a timestamp to a running TTimer instance, returning the index of the timestamp.
pure type(ttimer) function constructor ()
Constructor for the TTimer instances.
Private Attributes
integer ntimes
The number of timestamps stored.
integer maxtimes
The size of the timestamp list.
type(ttime), dimension(:), allocatable timestamps
Allocatable list of timestamps.
logical, dimension(:), allocatable timedinterval
logical indicating if the timer was running during an interval between two timestamps or not
logical running
True if the timer is running.
logical paused
True if the timer is paused.
logical stopped
True if the timer is stopped (final end)
Detailed Description
A class for keeping track of time in calculations, by creating a list of timestamps.
Definition at line 50 of file TimerClass.f03.
Member Function/Subroutine Documentation
addtimeflag()
procedure, pass, public timerclass::ttimer::addtimeflag
Add an additional timestamp without changing the status (running/paused) of the TTimer instance.
If the timer is stopped nothing will happen, and -1 is returned.
Parameters
[in,out] this The TTimer instance.
Returns
TS The index of the timestamp.
Definition at line 66 of file TimerClass.f03.
addtimestamp()
procedure, pass(this) timerclass::ttimer::addtimestamp private
Add a timestamp to a running TTimer instance, returning the index of the timestamp.
In case the timer is not running, nothing is done and -1 is returned.
Parameters
[in,out] this The TTimer instance.
Returns
TS The index of the timestamp.
Definition at line 74 of file TimerClass.f03.
assignment()
generic, public timerclass::ttimer::assignment
Function to copy one TTimer instance to the current one via the "=" assignment.
Parameters
[in,out] this The TTimer instance before the "=" assignment.
[in] from The TTimer instance after the "=" assignment.
Definition at line 75 of file TimerClass.f03.
References timeclass::copy().
constructor()
pure type(ttimer) function timerclass::ttimer::constructor private
Constructor for the TTimer instances.
Usage:
Type(TTimer) :: T
t=ttimer()
Returns
Returns a TTimer object
Definition at line 104 of file TimerClass.f03.
copy()
procedure, pass(this) timerclass::ttimer::copy private
Function to copy one TTimer instance to the current one via the "=" assignment.
Parameters
[in,out] this The TTimer instance before the "=" assignment.
[in] from The TTimer instance after the "=" assignment.
Definition at line 73 of file TimerClass.f03.
destructor()
final timerclass::ttimer::destructor final protected
Destructor of the TTimer class. Cleans up the instance upon finalization.
Parameters
[in,out] this The TTimer instance being destroyed automatically.
Definition at line 81 of file TimerClass.f03.
References timeclass::constructor(), and timeclass::destructor().
getelapsedtime()
generic, public timerclass::ttimer::getelapsedtime
Generic interface to the GetElapsedTime_total and GetElapsedTime_steps methods of the TTimer class.
Definition at line 76 of file TimerClass.f03.
References timerclass::getelapsedtime_steps(), and timerclass::getelapsedtime_total().
getelapsedtime_steps()
procedure, pass(this) timerclass::ttimer::getelapsedtime_steps private
Returns the number of seconds which elapsed between two timestamps. This is always a positive value.
NOTE:
If the timestamps are out of range, then -1 is returned.
If the start comes after end, then they are exchanged such that a positive time is obtained.
Parameters
[in] this The TTimer instance.
[in] Tstart,Tend The indices of the start and end time.
[in] INCL_PAUSE Logical indicating if the time during which the timer was paused should be included as well. [OPTIONAL, DEFAULT = .false. ]
Returns
Seconds The (fractional) number of seconds elapsed, as double precision real.
Definition at line 72 of file TimerClass.f03.
getelapsedtime_total()
procedure, pass(this) timerclass::ttimer::getelapsedtime_total private
Returns the number of seconds which elapsed between the start and stop timestamps.
Parameters
[in] this The TTimer instance.
[in] INCL_PAUSE Logical indicating if the time during which the timer was paused should be included as well. [OPTIONAL, DEFAULT = .false. ]
Returns
Seconds The (fractional) number of seconds elapsed, as double precision real.
Definition at line 71 of file TimerClass.f03.
getelapsedtimestring()
procedure, pass, public timerclass::ttimer::getelapsedtimestring
Returns a string representing the elapsed time. +.
Parameters
[in] this The TTimer instance.
[in] TSTART,TSTOP Indices of the start and end-times. [OPTIONAL, DEFAULT: TSTART=1, TSTOP=index of last timestamp]
[in] INCL_PAUSE Logical indicating if the time during which the timer was paused should be included as well. [OPTIONAL, DEFAULT = .false. ]
[in] FMT string indicating the format for the time-string.
sec : xxx.xxx secs
hms : xxxx h xx min xx.xxx secs
dhms: xx days xx h xx min xx.xxx secs
hour: xxx.xxx hours
day : xxx.xxx days [OPTIONAL, DEFAULT= sec]
Returns
str The string with the formatted time.
Definition at line 70 of file TimerClass.f03.
interrupt()
procedure, pass, public timerclass::ttimer::interrupt
Puts the TTimer instance on hold.
If the timer was not running nothing will happen. The optional IO parameter will return an error code.
IO values:
0 : all is well
-1 : The timer was not running, so nothing to pause.
-2 : The timer was already stopped/paused, so nothing to pause.
In case of error, TS will be set to -1.
Parameters
[in,out] this The TTimer instance.
[out] IO Optional parameter giving the error-status. [OPTIONAL ; DEFAULT= 0]
Returns
TS The index of the final timestamp.
Definition at line 64 of file TimerClass.f03.
printelapsedtimereport()
procedure, pass, public timerclass::ttimer::printelapsedtimereport
Print small timings report to unit UN.
Parameters
[in] this The TTimer instance.
[in] message String containing a message to include.
[in] Tstart,Tstop Integer indexes of the start and stop times
[in] UN Integer indicating the unit to write the report to.
[in] INCL_PAUSE Logical indicating if the time during which the timer was paused should be included as well. [OPTIONAL, DEFAULT = .false. ]
Definition at line 69 of file TimerClass.f03.
reset()
procedure, pass, public timerclass::ttimer::reset
Start the TTimer instance. If the timer was already running it is reset first.
Parameters
[in,out] this The TTimer instance.
Definition at line 68 of file TimerClass.f03.
resume()
procedure, pass, public timerclass::ttimer::resume
Restart the TTimer instance after a pause. If the timer is not paused, nothing will happen and TS=-1 is returned.
Parameters
[in,out] this The TTimer instance.
Returns
TS The index of the first timestamp.
Definition at line 65 of file TimerClass.f03.
start()
procedure, pass, public timerclass::ttimer::start
Start the TTimer instance (clean start, everything is reset). If the timer was already running it is reset first.
Parameters
[in,out] this The TTimer instance.
Returns
TS The index of the first timestamp.
Definition at line 63 of file TimerClass.f03.
stoptimer()
procedure, pass, public timerclass::ttimer::stoptimer
Stops the TTimer instance (terminal fashion...no restart possible).
If the timer was not running nothing will happen. The optional IO parameter will return an error code.
IO values:
0 : all is well
-1 : The timer was not running, so nothing to stop.
-2 : The timer was already stopped, so nothing to stop.
In case of error, TS will be set to -1.
Parameters
[in,out] this The TTimer instance.
[out] IO Optional parameter giving the error-status. [OPTIONAL ; DEFAULT= 0]
Returns
TS The index of the final timestamp.
Definition at line 67 of file TimerClass.f03.
Member Data Documentation
maxtimes
integer timerclass::ttimer::maxtimes private
The size of the timestamp list.
Definition at line 54 of file TimerClass.f03.
ntimes
integer timerclass::ttimer::ntimes private
The number of timestamps stored.
Definition at line 53 of file TimerClass.f03.
paused
logical timerclass::ttimer::paused private
True if the timer is paused.
Definition at line 59 of file TimerClass.f03.
running
logical timerclass::ttimer::running private
True if the timer is running.
Definition at line 58 of file TimerClass.f03.
stopped
logical timerclass::ttimer::stopped private
True if the timer is stopped (final end)
Definition at line 60 of file TimerClass.f03.
timedinterval
logical, dimension(:), allocatable timerclass::ttimer::timedinterval private
logical indicating if the timer was running during an interval between two timestamps or not
Definition at line 56 of file TimerClass.f03.
timestamps
type(ttime), dimension(:), allocatable timerclass::ttimer::timestamps private
Allocatable list of timestamps.
Definition at line 55 of file TimerClass.f03.
The documentation for this module was generated from the following file:
TimerClass.f03